#! /bin/bash

# Re-encode large video files with the HEVC encoder, it requires x265 and ffmpeg

for origin in *.*
 do
   mkdir resultDir
   result=`echo "$origin" | cut -d"." -f1 -s`
    echo "origin is $origin and resutl is $result.mp4"
        ffmpeg -i "${origin}" \
	       -c:v libx265 \
	       -preset ultrafast \
	       -x265-params crf=23:pools=2 \
	       -c:a libfdk_aac -b:a 128k \
	       "resultDir/${result}.mp4"
done
