#!/bin/bash

for file in "$1"/*.zip
    do
        file=`echo "$file" | rev | cut -d'/' -f 1 | rev | rev | cut -d'.' -f2- | rev`
        mkdir -p "$2/$file"
        unzip "$1/${file}.zip" -d "$2/$file"
    done
