#! /bin/bash

allowed=('avi' 'mp4' 'mkv')
for extension in ${allowed[@]}
    do
		for source in "$1"/*.$extension
			do
				if [ ! -f "$source" ]
					then
					continue
				fi
				result=`echo "$source" | rev | cut -d'/' -f 1 | rev | rev | cut -d'.' -f2- | rev`
				echo "source is $source and result is $result.ico"
                convert -density 384 "${source}" -define icon:auto-resize -transparent white "$2/${result}.ico"
			done
	done
