#!/bin/bash

if [ $# -eq 1 ]
    then
        NM=`uname -a && date`
        NAME=`echo $NM | md5sum | cut -f1 -d" "`
        ppa_name=`echo "$1" | cut -d":" -f2 -s`
        if [ -z "$ppa_name" ]
            then
                echo "PPA name not found"
                echo "a script to add PPA repositories to your Debian-based machine"
                echo "$0 ppa:user/ppa-name"
            else
                echo "$ppa_name"
                ppa_local=`echo "$1" | cut -d":" -f2 -s | cut -d"/" -f1 -s`
                release=`lsb_release -a | grep -e Codename | rev | cut -d":" -f 1 | rev`
                echo "deb http://ppa.launchpad.net/$ppa_name/ubuntu $release main" >> /etc/apt/sources.list.d/${ppa_local}.list
                apt-get update -o Dir::Etc::sourcelist="sources.list.d/${ppa_local}.list" -o Dir::Etc::sourceparts="-" -o APT::Get::List-Cleanup="0"  >> /dev/null 2> /tmp/${NAME}_apt_add_key.txt
                key=`cat /tmp/${NAME}_apt_add_key.txt | cut -d":" -f6 | cut -d" " -f3`
                apt-key adv --keyserver keyserver.ubuntu.com --recv-keys $key
                rm -rf /tmp/${NAME}_apt_add_key.txt
        fi
    else
        echo "a script to add PPA repositories to your Debian-based machine"
        echo "$0 ppa:user/ppa-name"
fi
