#!/bin/bash

allowed=('jpg' 'jpeg')
for extension in ${allowed[@]}
    do
		for file in "$1"/*.$extension
			do
				if [ ! -f ${file} ]
					then
					continue
				fi
				name=`echo "$file" | rev | cut -d'/' -f 1 | rev | rev | cut -d'.' -f2- | rev`
				echo "filename: $name"
				convert "$file" "$1/$name.ppm"
				potrace -s "$1/$name.ppm" -o "$2/$name.svg"
				rm -rf "$1/$name.ppm"
			done
	done
