#!/bin/bash

while [ -d "$1" ]; do
	echo "repository already exists!"
	echo "Please select an option:
	[o] override existing repository
	[e] exit"
	read -p "" num
	case "$num" in
		[o]* ) rm -rf "$1";;
		[e]* ) exit;;
		* ) echo "Please answer correctly";;
		esac
done

mkdir "$1"
cd "$1"
git init

# initial commit (of a dummy file)
touch deleteme.txt
git add .
git commit -m "Initial dummy commit"

vars=($@)
reponames=""

for old_repo in ${vars[@]:1}; do
	reponame=${old_repo##*/}
	# Fetching old_repo
	git remote add -f "$reponame" "$old_repo"

	# Merger from old_repo/master into new/master
	git merge "$reponame/master" -m "fetched from $reponame"
	
	if [ -f deleteme.txt ]; then
		# dummy file removal
		git rm ./deleteme.txt
		git commit -m "Clean up initial file"
	fi
	[[ !  -z  "$reponames"  ]] && reponames+="|"
	reponames+="^"
	reponames+="$reponame"
	# Moving the old_repo to its own subdirectory
	mkdir "$reponame"
	find * -maxdepth 0 | egrep -v "$reponames" | { while read name; do git mv "$name" "$reponame"; done }

	# Committing the final old_repo merger
	git commit -m "merged $old_repo as $reponame"
	git remote rm "$reponame"
done
